
#'creting our dict

mandinka = {'one':'kiling',
            'two':'fula',
            'three':'saba',
            'four':'nani',
            'five':'lulu',
            'six':'woro',
            'seven':'woro-wula',
            'eight':'sein',
            'nine':'kononto',
            'ten':'tang',
            'eleven':'tang-nin-kiling',
            'twelve':'tang-nin-fula',
            'thirteen':'tang-nin-saba',
            'fourteen':'tang-nin-nani',
            'fifteen':'tang-nin-lulu',
            'sixteen':'tang-nin-woro',
            'seventeen':'tang-nin-woro-wula',
            'eighteen':'tang-nin-sein',
            'nineteen':'tang-nin-kononto',
            'twenty':'muwang',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            #from 1 to 100
            #starting words
            'yes':'haa',
            'what':'mung',
            'go':'ta',
            'come':'ta',
            'book':'buko',
            'nose':'nungho',
            'eye':'nyaa',
            'head':'kuong',
            'shirt':'dendiko',
            'man':'keeou',
            'woman':'musoo',
            'girl':'sunkuto',
            'boy':'kangbanoo',
            'sit':'sei',
            'tree':'yero',
            'trouser':'kou-rr-to',
            'television':'tel-lea',
            'sex':'sukah, nuko-deh, duma-tan-tang',
            'house':'bu-nughoe',
            'compound':'korr-daa',
            'chair':'sei-ranghoe',
            'country':'ban-koo',
            'sand':'bang-koo',
            'plane':'kulung-tei-la',
            'butterfly':'kang-kula-bearo',
            'phone':'mobiloo',
            'mobile':'mobiloo',
            'telephone':'tele-funo',
            'white':'kooy-ma',
            'black':'fim-ma',
            'green':'jam-mba-kero',
            'blue':'bulu-wo',
            'red':'wulea-ma',
            'grey':'seaa-ma',
            'yellow':'neteh-munko',
            'leave':'a-bula',
            'body':'baloo',
            'shoulder':'kaboo',
            'finger':'bulu-kondinghoe',
            'hand':'bulo',
            'elbow':'no-nong-kunghoe',
            'hen':'see-seawo',
            'cheek':'tama-daa',
            'mouth':'daa',
            'ear':'tuloo',
            'pinna':'tulu-fito',
            'nostril':'nung-huwo',
            'buttocks':'buda',
            'teeth':'nyenghoe',
            'lips':'daa-turo',
            'hell':'jahhanama',
            'stomach':'konoo',
            'leg':'senghoe',
            'legs':'se-ngheol',
            'mind':'hakiloo',
            'heart':'jusoo',
            'penis':'fotoo',
            'vagina':'bea-wo',
            'lover':'ka-nu-mo',
            'friend':'kafu-nuo',
            'mates':'fulang-nghoe',
            'where':'minto',
            'finger nail':'n-hon-singhoe',
            'nail':'piray-koo',
            'spoon':'kojaroo',
            'glass':'galaso',
            'kettle':'tasal-leawo',
            'bottle':'kaboo',
            'hope':'hamoo',
            'faith':'gi-koo',
            'hat':'nafoo',
            'cap':'nafoo',
            'where are you going':'e-kah-taa-minto-leh',
            'horse':'suwo',
            'houseful':'seyoo',
            'school':'karang-bunghoe',
            'relatives':'badinghoe-l',
            'relative':'badinghoe',
            'parents':'wulu-lal',
            'parent':'wulu-la',
            'impregnate':'konoma',
            'sister':'baaring-muso',
            'sisters':'baaring-muso-lu',
            'brothers':'baaring-kewo-lu',
            'brother':'baaring-kewo',
            'cousin':'san-nau',
            'uncle':'baring',
            'anuty':'binki',
            'elder':'alfaa',
            'your elder':'e-la-alfaa',
            'my elder':'nu-na-alfaa',
            'younger':'dingdi-nghoe',
            'my younger':'nna-dingdi-nghoe',
            'your younger':'e-la-dingdi-ngoe',
            'siblings':'dokollu',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            












    }

word = input('Enter a word: ')
print('{1} = {0}, in mandinka'.format(mandinka.get(word),word))
'''def mandinka_word(word):
    mandinka1 = mandinka[word]
    for word in mandinka:
        return mandinka.get(word)
print('{0} = {1}'.format(mandinka_word(word)))'''




