
#'creting our dict

mandinka = {'one':'kiling',
            '1':'kiling',
            'two' and '2':'fula',
            'three' and '3':'saba',
            'four' and '4':'nani',
            'five' and '5':'lulu',
            'six' and '6':'woro',
            'seven' and '7':'woro-wula',
            'eight' and '8':'sein',
            'nine' and '9':'kononto',
            'ten' and '10':'tang',
            'eleven' and '11':'tang-nin-kiling',
            'twelve' and '12':'tang-nin-fula',
            'thirteen' and '13':'tang-nin-saba',
            'fourteen' and '14':'tang-nin-nani',
            'fifteen' and '15':'tang-nin-lulu',
            'sixteen' and '16':'tang-nin-woro',
            'seventeen' and '17':'tang-nin-woro-wula',
            'eighteen' and '18':'tang-nin-sein',
            'nineteen' and '19':'tang-nin-kononto',
            'twenty' and '20':'muwang',
            'twenty one' and '21':'muwang-nin-kiling',
            'twenty two' and '22':'muwang-nin-fula',
            'twenty three' and '23':'muwang-nin-saba',
            'twenty four' and '24':'muwang-nin-nani',
            'twenty five' and '25':'muwang-nin-lulu',
            'twenty six' and '26':'muwang-nin-woro',
            'twenty seven' and '27':'muwang-nin-woro-wula',
            'twenty eight' and '28':'muwang-nin-sein',
            'twenty nine' and '29':'muwang-nin-kononto',
            'thirty' and '30':'tang-saba',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            #from 1 to 100
            #starting words
            'yes':'haa',
            'what':'mung',
            'go':'ta',
            'come':'ta',
            'book':'buko',
            'nose':'nungho',
            'eye':'nyaa',
            'head':'kuong',
            'shirt':'dendiko',
            'man':'keeou',
            'woman':'musoo',
            'girl':'sunkuto',
            'boy':'kangbanoo',
            'sit':'sei',
            'tree':'yero',
            'trouser':'kou-rr-to',
            'television':'tel-lea',
            'sex':'sukah, nuko-deh, duma-tan-tang',
            'house':'bu-nughoe',
            'compound':'korr-daa',
            'chair':'sei-ranghoe',
            'country':'ban-koo',
            'sand':'bang-koo',
            'plane':'kulung-tei-la',
            'butterfly':'kang-kula-bearo',
            'phone':'mobiloo',
            'mobile':'mobiloo',
            'telephone':'tele-funo',
            'white':'kooy-ma',
            'black':'fim-ma',
            'green':'jam-mba-kero',
            'blue':'bulu-wo',
            'red':'wulea-ma',
            'grey':'seaa-ma',
            'yellow':'neteh-munko',
            'leave':'a-bula',
            'body':'baloo',
            'shoulder':'kaboo',
            'finger':'bulu-kondinghoe',
            'hand':'bulo',
            'elbow':'no-nong-kunghoe',
            'hen':'see-seawo',
            'cheek':'tama-daa',
            'mouth':'daa',
            'ear':'tuloo',
            'pinna':'tulu-fito',
            'nostril':'nung-huwo',
            'buttocks':'buda',
            'teeth':'nyenghoe',
            'lips':'daa-turo',
            'hell':'jahhanama',
            'stomach':'konoo',
            'leg':'senghoe',
            'legs':'se-ngheol',
            'mind':'hakiloo',
            'heart':'jusoo',
            'penis':'fotoo',
            'vagina':'bea-wo',
            'lover':'ka-nu-mo',
            'friend':'kafu-nuo',
            'mates':'fulang-nghoe',
            'where':'minto',
            'finger nail':'n-hon-singhoe',
            'nail':'piray-koo',
            'spoon':'kojaroo',
            'glass':'galaso',
            'kettle':'tasal-leawo',
            'bottle':'kaboo',
            'hope':'hamoo',
            'faith':'gi-koo',
            'hat':'nafoo',
            'cap':'nafoo',
            'where are you going':'e-kah-taa-minto-leh',
            'horse':'suwo',
            'houseful':'seyoo',
            'school':'karang-bunghoe',
            'relatives':'badinghoe-l',
            'relative':'badinghoe',
            'parents':'wulu-lal',
            'parent':'wulu-la',
            'impregnate':'konoma',
            'sister':'baaring-muso',
            'sisters':'baaring-muso-lu',
            'brothers':'baaring-kewo-lu',
            'brother':'baaring-kewo',
            'cousin':'san-nau',
            'uncle':'baring',
            'anuty':'binki',
            'elder':'alfaa',
            'your elder':'e-la-alfaa',
            'my elder':'nu-na-alfaa',
            'younger':'dingdi-nghoe',
            'my younger':'nna-dingdi-nghoe',
            'your younger':'e-la-dingdi-ngoe',
            'siblings':'dokollu',
            'money':'kodo',
            'where are you':'e-ba-min-to',
            'i am there':'m-bah-j-leh',
            'i called you':'n-ye-call-leh',
            'till tomorrow':'foe-somah',
            'today':'bee',
            'tomorrow':'saama',
            'next tomorrow':'c-nin-ding',
            'first':'folo',
            'second':'fulan-janghoe',
            'third':'saba-nja-ghoe',
            'fourth':'naning-ja-nghoe',
            'fifth':'lulu-njaghoe',
            'sixth':'woro-nja-nghoe',
            'yesterday':'kunung',
            'day before yesterday':'kunug-koo',
            'day':'tilo, lu-nghoe',
            'night':'sutoo',
            'morning':'somon-da',
            'evening':'tili-bulo',
            'wait':'e-ba-tung',
            'monday':'tene-nghoe',
            'days of the week':'',
            'months of the year':'',
            'tuesday':'talatoo',
            'wednesday':'ara-boo',
            'thursday':'ara-miso',
            'friday':'ar-jumo',
            'saturday':'cii-bi-to',
            'sunday':'demasoo',
            'peace':'kai-roo',
            'respect':'bu-nya',
            'discipline':'kulu',
            'shameless':'malu-bal-ya',
            'shame':'maloo',
            'they said':'e-koo',
            'he said':'ar-koo',
            'sun':'tilo',
            'moon':'karoo',
            'star':'lolo',
            'world':'dun-ya',
            'waste':'ti-nya-roo',
            'stars':'lolo-lu',
            'voice':'ka-nghoe',
            'neck':'ka-nghoe',
            'necklace':'kang-to-konna',
            'headtie':'tikoo',
            'ring':'bul-to-konna',
            'work':'doe-kuwo',
            'perfect':'',
            'good':'beh-te-ya',
            'sympathy':'balafaa',
            'son':'ding-kewo',
            'daughter':'ding-muso',
            'dog':'wuloo',
            'cat':'yang-kumoo',
            'sheep':'sagio',
            'goat':'baa',
            'cow':'niiso',
            'donkey':'falo',
            'donkey cart':'fal-sarae-to',
            'cart':'sarae-to',
            'carry':'sika',
            'hold':'muta',
            'monkey':'suloo',
            'there':'jana',
            'who':'juma',
            'they':'e-tol',
            'betray':'jangfaa',
            'up':'santoh',
            'down':'duuma',
            'bee':'kumoo',
            'betrayer':'jangfaa-la',
            'snake':'saa',
            'river':'baa',
            'try':'katah',
            'bracelet':'but-totaa',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            '':'',
            












    }
print('\t\t\t %---________________---%')
print('\t\t\t + Mandinka Dictionary  +' )
print('\t\t\t +Practice makes prefect+  ')
print('\t\t\t %___----------------___%   \n')
print('Type \'Exit\' to quit the Program\n')

while (True):
    word = input('Enter a word: ')
    word = word.lower()
    if (word != 'exit'):

        #name = input('Enter your name: ')
        print('{1} = {0}, in mandinka\n'.format(mandinka.get(word),word.upper()))
    else:
        print('Thanks for your time')
        break
'''def mandinka_word(word):
    mandinka1 = mandinka[word]
    for word in mandinka:
        return mandinka.get(word)
print('{0} = {1}'.format(mandinka_word(word)))'''

#####################################################
###### SEPERATE EXAMPLES, PHARSES AND THE LIKE ######
#####################################################

###future project
####the use of RE's to make patterns to match and join words, create sentences
####and numbers
