import turtle
from turtle import TurtleScreen
from turtle import bgcolor
from turtle import setworldcoordinates
from random import*
from random import randint as rand_int
'''import Tkinter
from Tkconstants import*'''
sam3 = rand_int(180,100000)
sam = turtle.Turtle()
sam.shape('turtle')

sam.begin_fill()
sam.fillcolor('yellow')
for i in [0,1,2,3]:
    sam.speed(2)
    #sam.color('maroon')
    sam.forward(150)
    sam.right(90)
    sam.backward(50)
sam.end_fill()
sam.begin_fill()
sam.fillcolor('red')
sam.left(45)
sam.forward(210)
sam.right(75)
#sam.color('green','red')
sam.forward(210)
sam.speed(3)
sam.right(137)
sam.forward(186)
sam.end_fill()
sam.begin_fill()
sam.fillcolor('yellow')
#sam.color('yellow')
sam.right(-78)
sam.speed(1)
sam.forward(103)
sam.left(105)
#sam.color('green','blue')
sam.forward(186)
sam.left(75)
sam.forward(93)
sam.end_fill()
sam.right(-102.4)
sam.forward(75)
sam.left(80)
#sam.color('green','green')
sam.speed(2)

sam.begin_fill()
sam.fillcolor('black')
sam.forward(95)
sam.right(76.5)
sam.forward(50)
sam.right(105)
#sam.color('green','pink')
sam.forward(100)
sam.speed(2)
sam.right(180)

sam.end_fill()

sam.forward(50)
sam.left(115)
sam.begin_fill()
sam.fillcolor('blue')
#sam.color('green','violet')
sam.forward(15)
sam.right(112)
sam.forward(15)
sam.right(75)
sam.forward(5)
sam.left(-96.5)
sam.forward(8)
#sam.color('green','orange')
sam.left(90)
sam.forward(7)
sam.left(-100)
#sam.circle(150,180)
sam.dot()
sam.end_fill()
sam.right(360)
sam.left(180)
sam.right(180)
sam.left(360)
sam.forward(55.01)
sam.left(-81.79)
sam.forward(122)
sam.left(360)
sam.right(360)
sam.left(360)
sam.left(137.2)
sam.forward(125)
sam.right(120)
sam.color('black')
sam.begin_fill()
sam.fillcolor('black')
sam.fd(225)
sam.right(180)
sam.forward(226.5)
sam.color('maroon')
sam.left(121)
sam.fd(125)
sam.right(60)
sam.fd(45)
sam.color('black')
sam.left(157.2)
sam.fd(242)
sam.right(180)
sam.left(180)
sam.right(360)
sam.left(360)
sam.end_fill()

#shadow
'''sam.begin_fill()
sam.fillcolor('black')
sam.forward(75)
sam.right(60)
sam.forward(100)
sam.right(55)
sam.fd(60)
sam.right(40)
sam.fd(75)
sam.end_fill()'''
sam.left(135)
sam.forward(254.3)
sam.color('maroon')
sam.left(127.5)
sam.forward(165)
sam.right(137)
sam.forward(123)

sam.left(80)
sam.forward(50)
sam.speed(2)
'''
frame = Tkinter.Frame(tk, relief=RIDGE, borderwidth=3) 
jawara = Tkinter.Button(frame,text='Click on me to Exit!',command=tk.destrroy)'''


sam.begin_poly()
sam.shapesize(12,15,3)
for i in range(0,1000):
        sam.color('red')
        sam.right(180)
        sam.color('blue','brown')
        sam.left(180)
        sam.shape('circle')
        sam.shape('triangle')
        sam.shape('turtle')
        sam.showturtle()
        sam.color('orange','pink')
        sam.right(360)
        sam.color('green')
        sam.left(360)
sam.end_poly()        






